version: '3.1'

networks:
  produto_net:
    driver: bridge

volumes:
  wordpress_vol:
  wordpress:

services:
  wordpress:
    image: wordpress:php8.0
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspwd
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspwd
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - wordpress_vol:/var/lib/mysql
